# Module 12 Challenge
## Deliverable 2: Scrape and Analyze Mars Weather Data

In [6]:
# Import relevant libraries
from splinter import Browser
from bs4 import BeautifulSoup as soup
from webdriver_manager.chrome import ChromeDriverManager
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
executable_path = {'executable_path': ChromeDriverManager().install()}
browser = Browser('chrome', **executable_path, headless=False)

====== WebDriver manager ======
Current google-chrome version is 111.0.5563
Get LATEST chromedriver version for 111.0.5563 google-chrome
Driver [C:\Users\kfbie\.wdm\drivers\chromedriver\win32\111.0.5563.64\chromedriver.exe] found in cache

### Step 1: Visit the Website

Use automated browsing to visit the [Mars Temperature Data Site](https://static.bc-edx.com/data/web/mars_facts/temperature.html). Inspect the page to identify which elements to scrape.

   > **Hint** To identify which elements to scrape, you might want to inspect the page by using Chrome DevTools to discover whether the table contains usable classes.

In [8]:
# Visit the website
url = 'https://static.bc-edx.com/data/web/mars_facts/temperature.html'
browser.visit(url)

### Step 2: Scrape the Table

Create a Beautiful Soup object and use it to scrape the data in the HTML table.

Note that this can also be achieved by using the Pandas `read_html` function. However, use Beautiful Soup here to continue sharpening your web scraping skills.

In [9]:
# Create a Beautiful Soup Object
html = browser.html
climate_soup = soup(html, 'html.parser')
print(climate_soup)

<html lang="en"><head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<meta content="" name="description"/>
<title>Mars Temperature Data</title>
<link href="css/bootstrap.min.5.2.2.css" rel="stylesheet" type="text/css"/>
<link href="css/temp.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<main>
<div class="container py-4">
<header class="pb-3 mb-4 border-bottom">
<a class="d-flex align-items-center text-dark text-decoration-none" href="/">
<span class="fs-4">Mission To Mars</span>
</a>
</header>
<div class="p-5 mb-4 bg-light rounded-3">
<div class="container-fluid py-5">
<h1 class="display-5 fw-bold">Mars Temperature Data</h1>
<p class="col-md-8 fs-4">This is Mars data.</p>
<table class="table">
<tbody><tr>
<th>id</th>
<th>terrestrial_date</th>
<th>sol</th>
<th>ls</th>
<th>month</th>
<th>min_temp</th>
<th>pressure</th>
</tr>
<tr class="data-row">
<td>2</td>
<td>2012-08-16</td>
<td>10</td>
<td>155</td>
<td>6</td>
<td>-75.0</td>
<td>739.0</td>
</tr>
<tr class="data-row">
<td>13</td>
<td>2012-08-17</td>
<td>11</td>
<td>156</td>
<td>6</td>
<td>-76.0</td>
<td>740.0</td>
</tr>
<tr class="data-row">
<td>24</td>
<td>2012-08-18</td>
<td>12</td>
<td>156</td>
<td>6</td>
<td>-76.0</td>
<td>741.0</td>
</tr>
<tr class="data-row">
<td>35</td>
<td>2012-08-19</td>
<td>13</td>
<td>157</td>
<td>6</td>
<td>-74.0</td>
<td>732.0</td>
</tr>
<tr class="data-row">
<td>46</td>
<td>2012-08-20</td>
<td>14</td>
<td>157</td>
<td>6</td>
<td>-74.0</td>
<td>740.0</td>
</tr>
<tr class="data-row">
<td>57</td>
<td>2012-08-21</td>
<td>15</td>
<td>158</td>
<td>6</td>
<td>-78.0</td>
<td>740.0</td>
</tr>
<tr class="data-row">
<td>68</td>
<td>2012-08-22</td>
<td>16</td>
<td>158</td>
<td>6</td>
<td>-77.0</td>
<td>740.0</td>
</tr>
<tr class="data-row">
<td>79</td>
<td>2012-08-23</td>
<td>17</td>
<td>159</td>
<td>6</td>
<td>-76.0</td>
<td>742.0</td>
</tr>
<tr class="data-row">
<td>112</td>
<td>2012-08-27</td>
<td>21</td>
<td>161</td>
<td>6</td>
<td>-74.0</td>
<td>741.0</td>
</tr>
<tr class="data-row">
<td>114</td>
<td>2012-08-28</td>
<td>22</td>
<td>162</td>
<td>6</td>
<td>-74.0</td>
<td>742.0</td>
</tr>
<tr class="data-row">
<td>123</td>
<td>2012-08-29</td>
<td>23</td>
<td>162</td>
<td>6</td>
<td>-75.0</td>
<td>741.0</td>
</tr>
<tr class="data-row">
<td>134</td>
<td>2012-08-30</td>
<td>24</td>
<td>163</td>
<td>6</td>
<td>-75.0</td>
<td>742.0</td>
</tr>
<tr class="data-row">
<td>145</td>
<td>2012-08-31</td>
<td>25</td>
<td>163</td>
<td>6</td>
<td>-75.0</td>
<td>743.0</td>
</tr>
<tr class="data-row">
<td>156</td>
<td>2012-09-01</td>
<td>26</td>
<td>164</td>
<td>6</td>
<td>-76.0</td>
<td>745.0</td>
</tr>
<tr class="data-row">
<td>163</td>
<td>2012-09-02</td>
<td>27</td>
<td>164</td>
<td>6</td>
<td>-75.0</td>
<td>743.0</td>
</tr>
<tr class="data-row">
<td>170</td>
<td>2012-09-03</td>
<td>28</td>
<td>165</td>
<td>6</td>
<td>-75.0</td>
<td>745.0</td>
</tr>
<tr class="data-row">
<td>171</td>
<td>2012-09-04</td>
<td>29</td>
<td>166</td>
<td>6</td>
<td>-75.0</td>
<td>747.0</td>
</tr>
<tr class="data-row">
<td>172</td>
<td>2012-09-05</td>
<td>30</td>
<td>166</td>
<td>6</td>
<td>-74.0</td>
<td>747.0</td>
</tr>
<tr class="data-row">
<td>173</td>
<td>2012-09-06</td>
<td>31</td>
<td>167</td>
<td>6</td>
<td>-74.0</td>
<td>745.0</td>
</tr>
<tr class="data-row">
<td>175</td>
<td>2012-09-08</td>
<td>33</td>
<td>168</td>
<td>6</td>
<td>-73.0</td>
<td>748.0</td>
</tr>
<tr class="data-row">
<td>176</td>
<td>2012-09-10</td>
<td>34</td>
<td>168</td>
<td>6</td>
<td>-73.0</td>
<td>748.0</td>
</tr>
<tr class="data-row">
<td>177</td>
<td>2012-09-11</td>
<td>35</td>
<td>169</td>
<td>6</td>
<td>-73.0</td>
<td>749.0</td>
</tr>
<tr class="data-row">
<td>178</td>
<td>2012-09-12</td>
<td>36</td>
<td>169</td>
<td>6</td>
<td>-73.0</td>
<td>750.0</td>
</tr>
<tr class="data-row">
<td>179</td>
<td>2012-09-13</td>
<td>37</td>
<td>170</td>
<td>6</td>
<td>-73.0</td>
<td>750.0</td>
</tr>
<tr class="data-row">
<td>180</td>
<td>2012-09-14</td>
<td>38</td>
<td>171</td>
<td>6</td>
<td>-73.0</td>
<td>750.0</td>
</tr>
<tr class="data-row">
<td>181</td>
<td>2012-09-15</td>
<td>39</td>
<td>171</td>
<td>6</td>
<td>-75.0</td>
<td>751.0</td>
</tr>
<tr class="data-row">
<td>182</td>
<td>2012-09-16</td>
<td>40</td>
<td>172</td>
<td>6</td>
<td>-75.0</td>
<td>753.0</td>
</tr>
<tr class="data-row">
<td>183</td>
<td>2012-09-17</td>
<td>41</td>
<td>172</td>
<td>6</td>
<td>-75.0</td>
<td>753.0</td>
</tr>
<tr class="data-row">
<td>184</td>
<td>2012-09-18</td>
<td>42</td>
<td>173</td>
<td>6</td>
<td>-75.0</td>
<td>754.0</td>
</tr>
<tr class="data-row">
<td>185</td>
<td>2012-09-19</td>
<td>43</td>
<td>173</td>
<td>6</td>
<td>-74.0</td>
<td>756.0</td>
</tr>
<tr class="data-row">
<td>186</td>
<td>2012-09-20</td>
<td>44</td>
<td>174</td>
<td>6</td>
<td>-75.0</td>
<td>757.0</td>
</tr>
<tr class="data-row">
<td>187</td>
<td>2012-09-21</td>
<td>45</td>
<td>175</td>
<td>6</td>
<td>-74.0</td>
<td>758.0</td>
</tr>
<tr class="data-row">
<td>188</td>
<td>2012-09-22</td>
<td>46</td>
<td>175</td>
<td>6</td>
<td>-74.0</td>
<td>758.0</td>
</tr>
<tr class="data-row">
<td>189</td>
<td>2012-09-23</td>
<td>47</td>
<td>176</td>
<td>6</td>
<td>-75.0</td>
<td>758.0</td>
</tr>
<tr class="data-row">
<td>190</td>
<td>2012-09-24</td>
<td>48</td>
<td>176</td>
<td>6</td>
<td>-75.0</td>
<td>759.0</td>
</tr>
<tr class="data-row">
<td>191</td>
<td>2012-09-25</td>
<td>49</td>
<td>177</td>
<td>6</td>
<td>-74.0</td>
<td>761.0</td>
</tr>
<tr class="data-row">
<td>192</td>
<td>2012-09-26</td>
<td>50</td>
<td>177</td>
<td>6</td>
<td>-72.0</td>
<td>761.0</td>
</tr>
<tr class="data-row">
<td>193</td>
<td>2012-09-27</td>
<td>51</td>
<td>178</td>
<td>6</td>
<td>-76.0</td>
<td>762.0</td>
</tr>
<tr class="data-row">
<td>194</td>
<td>2012-09-28</td>
<td>52</td>
<td>179</td>
<td>6</td>
<td>-74.0</td>
<td>762.0</td>
</tr>
<tr class="data-row">
<td>195</td>
<td>2012-09-29</td>
<td>53</td>
<td>179</td>
<td>6</td>
<td>-71.0</td>
<td>764.0</td>
</tr>
<tr class="data-row">
<td>196</td>
<td>2012-09-30</td>
<td>54</td>
<td>180</td>
<td>7</td>
<td>-72.0</td>
<td>766.0</td>
</tr>
<tr class="data-row">
<td>197</td>
<td>2012-10-01</td>
<td>55</td>
<td>180</td>
<td>7</td>
<td>-74.0</td>
<td>766.0</td>
</tr>
<tr class="data-row">
<td>198</td>
<td>2012-10-02</td>
<td>56</td>
<td>181</td>
<td>7</td>
<td>-73.0</td>
<td>768.0</td>
</tr>
<tr class="data-row">
<td>199</td>
<td>2012-10-03</td>
<td>57</td>
<td>181</td>
<td>7</td>
<td>-73.0</td>
<td>769.0</td>
</tr>
<tr class="data-row">
<td>200</td>
<td>2012-10-04</td>
<td>58</td>
<td>182</td>
<td>7</td>
<td>-74.0</td>
<td>769.0</td>
</tr>
<tr class="data-row">
<td>201</td>
<td>2012-10-05</td>
<td>59</td>
<td>183</td>
<td>7</td>
<td>-76.0</td>
<td>771.0</td>
</tr>
<tr class="data-row">
<td>202</td>
<td>2012-10-06</td>
<td>60</td>
<td>183</td>
<td>7</td>
<td>-75.0</td>
<td>772.0</td>
</tr>
<tr class="data-row">
<td>203</td>
<td>2012-10-07</td>
<td>61</td>
<td>184</td>
<td>7</td>
<td>-72.0</td>
<td>772.0</td>
</tr>
<tr class="data-row">
<td>204</td>
<td>2012-10-08</td>
<td>62</td>
<td>184</td>
<td>7</td>
<td>-72.0</td>
<td>774.0</td>
</tr>
<tr class="data-row">
<td>205</td>
<td>2012-10-09</td>
<td>63</td>
<td>185</td>
<td>7</td>
<td>-73.0</td>
<td>775.0</td>
</tr>
<tr class="data-row">
<td>206</td>
<td>2012-10-10</td>
<td>64</td>
<td>186</td>
<td>7</td>
<td>-74.0</td>
<td>776.0</td>
</tr>
<tr class="data-row">
<td>207</td>
<td>2012-10-11</td>
<td>65</td>
<td>186</td>
<td>7</td>
<td>-72.0</td>
<td>777.0</td>
</tr>
<tr class="data-row">
<td>208</td>
<td>2012-10-12</td>
<td>66</td>
<td>187</td>
<td>7</td>
<td>-73.0</td>
<td>778.0</td>
</tr>
<tr class="data-row">
<td>209</td>
<td>2012-10-13</td>
<td>67</td>
<td>187</td>
<td>7</td>
<td>-73.0</td>
<td>780.0</td>
</tr>
<tr class="data-row">
<td>210</td>
<td>2012-10-14</td>
<td>68</td>
<td>188</td>
<td>7</td>
<td>-71.0</td>
<td>781.0</td>
</tr>
<tr class="data-row">
<td>211</td>
<td>2012-10-15</td>
<td>69</td>
<td>189</td>
<td>7</td>
<td>-73.0</td>
<td>778.0</td>
</tr>
<tr class="data-row">
<td>212</td>
<td>2012-10-17</td>
<td>70</td>
<td>189</td>
<td>7</td>
<td>-72.0</td>
<td>783.0</td>
</tr>
<tr class="data-row">
<td>213</td>
<td>2012-10-18</td>
<td>71</td>
<td>190</td>
<td>7</td>
<td>-71.0</td>
<td>784.0</td>
</tr>
<tr class="data-row">
<td>214</td>
<td>2012-10-19</td>
<td>72</td>
<td>190</td>
<td>7</td>
<td>-73.0</td>
<td>785.0</td>
</tr>
<tr class="data-row">
<td>215</td>
<td>2012-10-20</td>
<td>73</td>
<td>191</td>
<td>7</td>
<td>-70.0</td>
<td>788.0</td>
</tr>
<tr class="data-row">
<td>216</td>
<td>2012-10-21</td>
<td>74</td>
<td>192</td>
<td>7</td>
<td>-72.0</td>
<td>790.0</td>
</tr>
<tr class="data-row">
<td>217</td>
<td>2012-10-22</td>
<td>75</td>
<td>192</td>
<td>7</td>
<td>-73.0</td>
<td>791.0</td>
</tr>
<tr class="data-row">
<td>218</td>
<td>2012-10-23</td>
<td>76</td>
<td>193</td>
<td>7</td>
<td>-73.0</td>
<td>792.0</td>
</tr>
<tr class="data-row">
<td>219</td>
<td>2012-10-24</td>
<td>77</td>
<td>193</td>
<td>7</td>
<td>-71.0</td>
<td>792.0</td>
</tr>
<tr class="data-row">
<td>220</td>
<td>2012-10-25</td>
<td>78</td>
<td>194</td>
<td>7</td>
<td>-71.0</td>
<td>793.0</td>
</tr>
<tr class="data-row">
<td>221</td>
<td>2012-10-26</td>
<td>79</td>
<td>195</td>
<td>7</td>
<td>-73.0</td>
<td>795.0</td>
</tr>
<tr class="data-row">
<td>222</td>
<td>2012-10-27</td>
<td>80</td>
<td>195</td>
<td>7</td>
<td>-70.0</td>
<td>796.0</td>
</tr>
<tr class="data-row">
<td>223</td>
<td>2012-10-28</td>
<td>81</td>
<td>196</td>
<td>7</td>
<td>-72.0</td>
<td>798.0</td>
</tr>
<tr class="data-row">
<td>224</td>
<td>2012-10-29</td>
<td>82</td>
<td>196</td>
<td>7</td>
<td>-72.0</td>
<td>799.0</td>
</tr>
<tr class="data-row">
<td>225</td>
<td>2012-10-30</td>
<td>83</td>
<td>197</td>
<td>7</td>
<td>-72.0</td>
<td>801.0</td>
</tr>
<tr class="data-row">
<td>226</td>
<td>2012-10-31</td>
<td>84</td>
<td>198</td>
<td>7</td>
<td>-70.0</td>
<td>801.0</td>
</tr>
<tr class="data-row">
<td>227</td>
<td>2012-11-01</td>
<td>85</td>
<td>198</td>
<td>7</td>
<td>-71.0</td>
<td>805.0</td>
</tr>
<tr class="data-row">
<td>228</td>
<td>2012-11-02</td>
<td>86</td>
<td>199</td>
<td>7</td>
<td>-71.0</td>
<td>808.0</td>
</tr>
<tr class="data-row">
<td>229</td>
<td>2012-11-03</td>
<td>87</td>
<td>199</td>
<td>7</td>
<td>-70.0</td>
<td>808.0</td>
</tr>
<tr class="data-row">
<td>230</td>
<td>2012-11-04</td>
<td>88</td>
<td>200</td>
<td>7</td>
<td>-70.0</td>
<td>811.0</td>
</tr>
<tr class="data-row">
<td>231</td>
<td>2012-11-05</td>
<td>89</td>
<td>201</td>
<td>7</td>
<td>-73.0</td>
<td>813.0</td>
</tr>
<tr class="data-row">
<td>233</td>
<td>2012-11-06</td>
<td>90</td>
<td>201</td>
<td>7</td>
<td>-71.0</td>
<td>813.0</td>
</tr>
<tr class="data-row">
<td>234</td>
<td>2012-11-07</td>
<td>91</td>
<td>202</td>
<td>7</td>
<td>-74.0</td>
<td>817.0</td>
</tr>
<tr class="data-row">
<td>235</td>
<td>2012-11-08</td>
<td>92</td>
<td>202</td>
<td>7</td>
<td>-74.0</td>
<td>820.0</td>
</tr>
<tr class="data-row">
<td>236</td>
<td>2012-11-09</td>
<td>93</td>
<td>203</td>
<td>7</td>
<td>-72.0</td>
<td>819.0</td>
</tr>
<tr class="data-row">
<td>237</td>
<td>2012-11-10</td>
<td>94</td>
<td>204</td>
<td>7</td>
<td>-70.0</td>
<td>822.0</td>
</tr>
<tr class="data-row">
<td>238</td>
<td>2012-11-11</td>
<td>95</td>
<td>204</td>
<td>7</td>
<td>-68.0</td>
<td>822.0</td>
</tr>
<tr class="data-row">
<td>239</td>
<td>2012-11-12</td>
<td>96</td>
<td>205</td>
<td>7</td>
<td>-71.0</td>
<td>826.0</td>
</tr>
<tr class="data-row">
<td>240</td>
<td>2012-11-13</td>
<td>97</td>
<td>206</td>
<td>7</td>
<td>-68.0</td>
<td>828.0</td>
</tr>
<tr class="data-row">
<td>241</td>
<td>2012-11-14</td>
<td>98</td>
<td>206</td>
<td>7</td>
<td>-68.0</td>
<td>828.0</td>
</tr>
<tr class="data-row">
<td>242</td>
<td>2012-11-15</td>
<td>99</td>
<td>207</td>
<td>7</td>
<td>-68.0</td>
<td>829.0</td>
</tr>
<tr class="data-row">
<td>3</td>
<td>2012-11-16</td>
<td>100</td>
<td>207</td>
<td>7</td>
<td>-66.0</td>
<td>829.0</td>
</tr>
<tr class="data-row">
<td>4</td>
<td>2012-11-17</td>
<td>101</td>
<td>208</td>
<td>7</td>
<td>-65.0</td>
<td>830.0</td>
</tr>
<tr class="data-row">
<td>5</td>
<td>2012-11-18</td>
<td>102</td>
<td>209</td>
<td>7</td>
<td>-67.0</td>
<td>833.0</td>
</tr>
<tr class="data-row">
<td>6</td>
<td>2012-11-19</td>
<td>103</td>
<td>209</td>
<td>7</td>
<td>-66.0</td>
<td>836.0</td>
</tr>
<tr class="data-row">
<td>7</td>
<td>2012-11-20</td>
<td>104</td>
<td>210</td>
<td>8</td>
<td>-67.0</td>
<td>838.0</td>
</tr>
<tr class="data-row">
<td>8</td>
<td>2012-11-21</td>
<td>105</td>
<td>211</td>
<td>8</td>
<td>-66.0</td>
<td>839.0</td>
</tr>
<tr class="data-row">
<td>9</td>
<td>2012-11-23</td>
<td>106</td>
<td>211</td>
<td>8</td>
<td>-66.0</td>
<td>841.0</td>
</tr>
<tr class="data-row">
<td>10</td>
<td>2012-11-24</td>
<td>107</td>
<td>212</td>
<td>8</td>
<td>-66.0</td>
<td>844.0</td>
</tr>
<tr class="data-row">
<td>11</td>
<td>2012-11-25</td>
<td>108</td>
<td>212</td>
<td>8</td>
<td>-65.0</td>
<td>845.0</td>
</tr>
<tr class="data-row">
<td>12</td>
<td>2012-11-26</td>
<td>109</td>
<td>213</td>
<td>8</td>
<td>-64.0</td>
<td>844.0</td>
</tr>
<tr class="data-row">
<td>14</td>
<td>2012-11-27</td>
<td>110</td>
<td>214</td>
<td>8</td>
<td>-65.0</td>
<td>848.0</td>
</tr>
<tr class="data-row">
<td>15</td>
<td>2012-11-28</td>
<td>111</td>
<td>214</td>
<td>8</td>
<td>-66.0</td>
<td>849.0</td>
</tr>
<tr class="data-row">
<td>16</td>
<td>2012-11-29</td>
<td>112</td>
<td>215</td>
<td>8</td>
<td>-65.0</td>
<td>852.0</td>
</tr>
<tr class="data-row">
<td>17</td>
<td>2012-11-30</td>
<td>113</td>
<td>216</td>
<td>8</td>
<td>-66.0</td>
<td>857.0</td>
</tr>
<tr class="data-row">
<td>18</td>
<td>2012-12-01</td>
<td>114</td>
<td>216</td>
<td>8</td>
<td>-69.0</td>
<td>857.0</td>
</tr>
<tr class="data-row">
<td>19</td>
<td>2012-12-02</td>
<td>115</td>
<td>217</td>
<td>8</td>
<td>-66.0</td>
<td>857.0</td>
</tr>
<tr class="data-row">
<td>20</td>
<td>2012-12-03</td>
<td>116</td>
<td>217</td>
<td>8</td>
<td>-67.0</td>
<td>859.0</td>
</tr>
<tr class="data-row">
<td>21</td>
<td>2012-12-04</td>
<td>117</td>
<td>218</td>
<td>8</td>
<td>-66.0</td>
<td>861.0</td>
</tr>
<tr class="data-row">
<td>22</td>
<td>2012-12-05</td>
<td>118</td>
<td>219</td>
<td>8</td>
<td>-65.0</td>
<td>864.0</td>
</tr>
<tr class="data-row">
<td>23</td>
<td>2012-12-06</td>
<td>119</td>
<td>219</td>
<td>8</td>
<td>-66.0</td>
<td>866.0</td>
</tr>
<tr class="data-row">
<td>25</td>
<td>2012-12-07</td>
<td>120</td>
<td>220</td>
<td>8</td>
<td>-67.0</td>
<td>867.0</td>
</tr>
<tr class="data-row">
<td>26</td>
<td>2012-12-08</td>
<td>121</td>
<td>221</td>
<td>8</td>
<td>-66.0</td>
<td>869.0</td>
</tr>
<tr class="data-row">
<td>27</td>
<td>2012-12-09</td>
<td>122</td>
<td>221</td>
<td>8</td>
<td>-65.0</td>
<td>869.0</td>
</tr>
<tr class="data-row">
<td>28</td>
<td>2012-12-10</td>
<td>123</td>
<td>222</td>
<td>8</td>
<td>-66.0</td>
<td>875.0</td>
</tr>
<tr class="data-row">
<td>29</td>
<td>2012-12-11</td>
<td>124</td>
<td>223</td>
<td>8</td>
<td>-66.0</td>
<td>876.0</td>
</tr>
<tr class="data-row">
<td>30</td>
<td>2012-12-12</td>
<td>125</td>
<td>223</td>
<td>8</td>
<td>-68.0</td>
<td>880.0</td>
</tr>
<tr class="data-row">
<td>31</td>
<td>2012-12-13</td>
<td>126</td>
<td>224</td>
<td>8</td>
<td>-66.0</td>
<td>880.0</td>
</tr>
<tr class="data-row">
<td>32</td>
<td>2012-12-14</td>
<td>127</td>
<td>224</td>
<td>8</td>
<td>-67.0</td>
<td>884.0</td>
</tr>
<tr class="data-row">
<td>33</td>
<td>2012-12-15</td>
<td>128</td>
<td>225</td>
<td>8</td>
<td>-67.0</td>
<td>883.0</td>
</tr>
<tr class="data-row">
<td>34</td>
<td>2012-12-16</td>
<td>129</td>
<td>226</td>
<td>8</td>
<td>-65.0</td>
<td>886.0</td>
</tr>
<tr class="data-row">
<td>36</td>
<td>2012-12-17</td>
<td>130</td>
<td>226</td>
<td>8</td>
<td>-65.0</td>
<td>888.0</td>
</tr>
<tr class="data-row">
<td>37</td>
<td>2012-12-18</td>
<td>131</td>
<td>227</td>
<td>8</td>
<td>-65.0</td>
<td>889.0</td>
</tr>
<tr class="data-row">
<td>38</td>
<td>2012-12-19</td>
<td>132</td>
<td>228</td>
<td>8</td>
<td>-65.0</td>
<td>890.0</td>
</tr>
<tr class="data-row">
<td>39</td>
<td>2012-12-20</td>
<td>133</td>
<td>228</td>
<td>8</td>
<td>-65.0</td>
<td>891.0</td>
</tr>
<tr class="data-row">
<td>40</td>
<td>2012-12-21</td>
<td>134</td>
<td>229</td>
<td>8</td>
<td>-67.0</td>
<td>893.0</td>
</tr>
<tr class="data-row">
<td>41</td>
<td>2012-12-22</td>
<td>135</td>
<td>230</td>
<td>8</td>
<td>-65.0</td>
<td>894.0</td>
</tr>
<tr class="data-row">
<td>42</td>
<td>2012-12-23</td>
<td>136</td>
<td>230</td>
<td>8</td>
<td>-65.0</td>
<td>897.0</td>
</tr>
<tr class="data-row">
<td>43</td>
<td>2012-12-24</td>
<td>137</td>
<td>231</td>
<td>8</td>
<td>-64.0</td>
<td>896.0</td>
</tr>
<tr class="data-row">
<td>44</td>
<td>2012-12-25</td>
<td>138</td>
<td>232</td>
<td>8</td>
<td>-65.0</td>
<td>899.0</td>
</tr>
<tr class="data-row">
<td>45</td>
<td>2012-12-26</td>
<td>139</td>
<td>232</td>
<td>8</td>
<td>-66.0</td>
<td>899.0</td>
</tr>
<tr class="data-row">
<td>47</td>
<td>2012-12-27</td>
<td>140</td>
<td>233</td>
<td>8</td>
<td>-66.0</td>
<td>903.0</td>
</tr>
<tr class="data-row">
<td>48</td>
<td>2012-12-28</td>
<td>141</td>
<td>233</td>
<td>8</td>
<td>-64.0</td>
<td>904.0</td>
</tr>
<tr class="data-row">
<td>49</td>
<td>2012-12-29</td>
<td>142</td>
<td>234</td>
<td>8</td>
<td>-65.0</td>
<td>906.0</td>
</tr>
<tr class="data-row">
<td>50</td>
<td>2012-12-31</td>
<td>143</td>
<td>235</td>
<td>8</td>
<td>-63.0</td>
<td>908.0</td>
</tr>
<tr class="data-row">
<td>51</td>
<td>2013-01-01</td>
<td>144</td>
<td>235</td>
<td>8</td>
<td>-64.0</td>
<td>907.0</td>
</tr>
<tr class="data-row">
<td>52</td>
<td>2013-01-02</td>
<td>145</td>
<td>236</td>
<td>8</td>
<td>-64.0</td>
<td>909.0</td>
</tr>
<tr class="data-row">
<td>53</td>
<td>2013-01-03</td>
<td>146</td>
<td>237</td>
<td>8</td>
<td>-65.0</td>
<td>908.0</td>
</tr>
<tr class="data-row">
<td>54</td>
<td>2013-01-04</td>
<td>147</td>
<td>237</td>
<td>8</td>
<td>-65.0</td>
<td>914.0</td>
</tr>
<tr class="data-row">
<td>55</td>
<td>2013-01-05</td>
<td>148</td>
<td>238</td>
<td>8</td>
<td>-65.0</td>
<td>912.0</td>
</tr>
<tr class="data-row">
<td>56</td>
<td>2013-01-06</td>
<td>149</td>
<td>239</td>
<td>8</td>
<td>-65.0</td>
<td>914.0</td>
</tr>
<tr class="data-row">
<td>58</td>
<td>2013-01-07</td>
<td>150</td>
<td>239</td>
<td>8</td>
<td>-64.0</td>
<td>913.0</td>
</tr>
<tr class="data-row">
<td>59</td>
<td>2013-01-08</td>
<td>151</td>
<td>240</td>
<td>9</td>
<td>-65.0</td>
<td>915.0</td>
</tr>
<tr class="data-row">
<td>60</td>
<td>2013-01-09</td>
<td>152</td>
<td>241</td>
<td>9</td>
<td>-63.0</td>
<td>914.0</td>
</tr>
<tr class="data-row">
<td>61</td>
<td>2013-01-10</td>
<td>153</td>
<td>241</td>
<td>9</td>
<td>-65.0</td>
<td>915.0</td>
</tr>
<tr class="data-row">
<td>62</td>
<td>2013-01-11</td>
<td>154</td>
<td>242</td>
<td>9</td>
<td>-65.0</td>
<td>917.0</td>
</tr>
<tr class="data-row">
<td>63</td>
<td>2013-01-12</td>
<td>155</td>
<td>243</td>
<td>9</td>
<td>-64.0</td>
<td>917.0</td>
</tr>
<tr class="data-row">
<td>64</td>
<td>2013-01-13</td>
<td>156</td>
<td>243</td>
<td>9</td>
<td>-65.0</td>
<td>922.0</td>
</tr>
<tr class="data-row">
<td>65</td>
<td>2013-01-14</td>
<td>157</td>
<td>244</td>
<td>9</td>
<td>-64.0</td>
<td>920.0</td>
</tr>
<tr class="data-row">
<td>66</td>
<td>2013-01-15</td>
<td>158</td>
<td>245</td>
<td>9</td>
<td>-66.0</td>
<td>922.0</td>
</tr>
<tr class="data-row">
<td>67</td>
<td>2013-01-16</td>
<td>159</td>
<td>245</td>
<td>9</td>
<td>-65.0</td>
<td>918.0</td>
</tr>
<tr class="data-row">
<td>69</td>
<td>2013-01-17</td>
<td>160</td>
<td>246</td>
<td>9</td>
<td>-67.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>70</td>
<td>2013-01-18</td>
<td>161</td>
<td>246</td>
<td>9</td>
<td>-65.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>71</td>
<td>2013-01-19</td>
<td>162</td>
<td>247</td>
<td>9</td>
<td>-65.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>72</td>
<td>2013-01-20</td>
<td>163</td>
<td>248</td>
<td>9</td>
<td>-65.0</td>
<td>919.0</td>
</tr>
<tr class="data-row">
<td>73</td>
<td>2013-01-21</td>
<td>164</td>

In [10]:
# Extract all rows of data
data_rows = climate_soup.find_all('tr')
data_rows

[<tr>
 <th>id</th>
 <th>terrestrial_date</th>
 <th>sol</th>
 <th>ls</th>
 <th>month</th>
 <th>min_temp</th>
 <th>pressure</th>
 </tr>,
 <tr class="data-row">
 <td>2</td>
 <td>2012-08-16</td>
 <td>10</td>
 <td>155</td>
 <td>6</td>
 <td>-75.0</td>
 <td>739.0</td>
 </tr>,
 <tr class="data-row">
 <td>13</td>
 <td>2012-08-17</td>
 <td>11</td>
 <td>156</td>
 <td>6</td>
 <td>-76.0</td>
 <td>740.0</td>
 </tr>,
 <tr class="data-row">
 <td>24</td>
 <td>2012-08-18</td>
 <td>12</td>
 <td>156</td>
 <td>6</td>
 <td>-76.0</td>
 <td>741.0</td>
 </tr>,
 <tr class="data-row">
 <td>35</td>
 <td>2012-08-19</td>
 <td>13</td>
 <td>157</td>
 <td>6</td>
 <td>-74.0</td>
 <td>732.0</td>
 </tr>,
 <tr class="data-row">
 <td>46</td>
 <td>2012-08-20</td>
 <td>14</td>
 <td>157</td>
 <td>6</td>
 <td>-74.0</td>
 <td>740.0</td>
 </tr>,
 <tr class="data-row">
 <td>57</td>
 <td>2012-08-21</td>
 <td>15</td>
 <td>158</td>
 <td>6</td>
 <td>-78.0</td>
 <td>740.0</td>
 </tr>,
 <tr class="data-row">
 <td>68</td>
 <td>2012-08-22</td>
 <td>16</td>
 <td>158</td>
 <td>6</td>
 <td>-77.0</td>
 <td>740.0</td>
 </tr>,
 <tr class="data-row">
 <td>79</td>
 <td>2012-08-23</td>
 <td>17</td>
 <td>159</td>
 <td>6</td>
 <td>-76.0</td>
 <td>742.0</td>
 </tr>,
 <tr class="data-row">
 <td>112</td>
 <td>2012-08-27</td>
 <td>21</td>
 <td>161</td>
 <td>6</td>
 <td>-74.0</td>
 <td>741.0</td>
 </tr>,
 <tr class="data-row">
 <td>114</td>
 <td>2012-08-28</td>
 <td>22</td>
 <td>162</td>
 <td>6</td>
 <td>-74.0</td>
 <td>742.0</td>
 </tr>,
 <tr class="data-row">
 <td>123</td>
 <td>2012-08-29</td>
 <td>23</td>
 <td>162</td>
 <td>6</td>
 <td>-75.0</td>
 <td>741.0</td>
 </tr>,
 <tr class="data-row">
 <td>134</td>
 <td>2012-08-30</td>
 <td>24</td>
 <td>163</td>
 <td>6</td>
 <td>-75.0</td>
 <td>742.0</td>
 </tr>,
 <tr class="data-row">
 <td>145</td>
 <td>2012-08-31</td>
 <td>25</td>
 <td>163</td>
 <td>6</td>
 <td>-75.0</td>
 <td>743.0</td>
 </tr>,
 <tr class="data-row">
 <td>156</td>
 <td>2012-09-01</td>
 <td>26</td>
 <td>164</td>
 <td>6</td>
 <td>-76.0</td>
 <td>745.0</td>
 </tr>,
 <tr class="data-row">
 <td>163</td>
 <td>2012-09-02</td>
 <td>27</td>
 <td>164</td>
 <td>6</td>
 <td>-75.0</td>
 <td>743.0</td>
 </tr>,
 <tr class="data-row">
 <td>170</td>
 <td>2012-09-03</td>
 <td>28</td>
 <td>165</td>
 <td>6</td>
 <td>-75.0</td>
 <td>745.0</td>
 </tr>,
 <tr class="data-row">
 <td>171</td>
 <td>2012-09-04</td>
 <td>29</td>
 <td>166</td>
 <td>6</td>
 <td>-75.0</td>
 <td>747.0</td>
 </tr>,
 <tr class="data-row">
 <td>172</td>
 <td>2012-09-05</td>
 <td>30</td>
 <td>166</td>
 <td>6</td>
 <td>-74.0</td>
 <td>747.0</td>
 </tr>,
 <tr class="data-row">
 <td>173</td>
 <td>2012-09-06</td>
 <td>31</td>
 <td>167</td>
 <td>6</td>
 <td>-74.0</td>
 <td>745.0</td>
 </tr>,
 <tr class="data-row">
 <td>175</td>
 <td>2012-09-08</td>
 <td>33</td>
 <td>168</td>
 <td>6</td>
 <td>-73.0</td>
 <td>748.0</td>
 </tr>,
 <tr class="data-row">
 <td>176</td>
 <td>2012-09-10</td>
 <td>34</td>
 <td>168</td>
 <td>6</td>
 <td>-73.0</td>
 <td>748.0</td>
 </tr>,
 <tr class="data-row">
 <td>177</td>
 <td>2012-09-11</td>
 <td>35</td>
 <td>169</td>
 <td>6</td>
 <td>-73.0</td>
 <td>749.0</td>
 </tr>,
 <tr class="data-row">
 <td>178</td>
 <td>2012-09-12</td>
 <td>36</td>
 <td>169</td>
 <td>6</td>
 <td>-73.0</td>
 <td>750.0</td>
 </tr>,
 <tr class="data-row">
 <td>179</td>
 <td>2012-09-13</td>
 <td>37</td>
 <td>170</td>
 <td>6</td>
 <td>-73.0</td>
 <td>750.0</td>
 </tr>,
 <tr class="data-row">
 <td>180</td>
 <td>2012-09-14</td>
 <td>38</td>
 <td>171</td>
 <td>6</td>
 <td>-73.0</td>
 <td>750.0</td>
 </tr>,
 <tr class="data-row">
 <td>181</td>
 <td>2012-09-15</td>
 <td>39</td>
 <td>171</td>
 <td>6</td>
 <td>-75.0</td>
 <td>751.0</td>
 </tr>,
 <tr class="data-row">
 <td>182</td>
 <td>2012-09-16</td>
 <td>40</td>
 <td>172</td>
 <td>6</td>
 <td>-75.0</td>
 <td>753.0</td>
 </tr>,
 <tr class="data-row">
 <td>183</td>
 <td>2012-09-17</td>
 <td>41</td>
 <td>172</td>
 <td>6</td>
 <td>-75.0</td>
 <td>753.0</td>
 </tr>,
 <tr class="data-row">
 <td>184</td>
 <td>2012-09-18</td>
 <td>42</td>
 <td>173</td>
 <td>6</td>
 <td>-75.0</td>
 <td>754.0</td>
 </tr>,
 <tr class="data-row">
 <td>185</td>
 <td>2012-09-19</td>
 <td>43</td>
 <td>173</td>
 <td>6</td>
 <td>-74.0</td>
 <td>756.0</td>
 </tr>,
 <tr class="data-row">
 <td>186</td>
 <td>2012-09-20</td>
 <td>44</td>
 <td>174</td>
 <td>6</td>
 <td>-75.0</td>
 <td>757.0</td>
 </tr>,
 <tr class="data-row">
 <td>187</td>
 <td>2012-09-21</td>
 <td>45</td>
 <td>175</td>
 <td>6</td>
 <td>-74.0</td>
 <td>758.0</td>
 </tr>,
 <tr class="data-row">
 <td>188</td>
 <td>2012-09-22</td>
 <td>46</td>
 <td>175</td>
 <td>6</td>
 <td>-74.0</td>
 <td>758.0</td>
 </tr>,
 <tr class="data-row">
 <td>189</td>
 <td>2012-09-23</td>
 <td>47</td>
 <td>176</td>
 <td>6</td>
 <td>-75.0</td>
 <td>758.0</td>
 </tr>,
 <tr class="data-row">
 <td>190</td>
 <td>2012-09-24</td>
 <td>48</td>
 <td>176</td>
 <td>6</td>
 <td>-75.0</td>
 <td>759.0</td>
 </tr>,
 <tr class="data-row">
 <td>191</td>
 <td>2012-09-25</td>
 <td>49</td>
 <td>177</td>
 <td>6</td>
 <td>-74.0</td>
 <td>761.0</td>
 </tr>,
 <tr class="data-row">
 <td>192</td>
 <td>2012-09-26</td>
 <td>50</td>
 <td>177</td>
 <td>6</td>
 <td>-72.0</td>
 <td>761.0</td>
 </tr>,
 <tr class="data-row">
 <td>193</td>
 <td>2012-09-27</td>
 <td>51</td>
 <td>178</td>
 <td>6</td>
 <td>-76.0</td>
 <td>762.0</td>
 </tr>,
 <tr class="data-row">
 <td>194</td>
 <td>2012-09-28</td>
 <td>52</td>
 <td>179</td>
 <td>6</td>
 <td>-74.0</td>
 <td>762.0</td>
 </tr>,
 <tr class="data-row">
 <td>195</td>
 <td>2012-09-29</td>
 <td>53</td>
 <td>179</td>
 <td>6</td>
 <td>-71.0</td>
 <td>764.0</td>
 </tr>,
 <tr class="data-row">
 <td>196</td>
 <td>2012-09-30</td>
 <td>54</td>
 <td>180</td>
 <td>7</td>
 <td>-72.0</td>
 <td>766.0</td>
 </tr>,
 <tr class="data-row">
 <td>197</td>
 <td>2012-10-01</td>
 <td>55</td>
 <td>180</td>
 <td>7</td>
 <td>-74.0</td>
 <td>766.0</td>
 </tr>,
 <tr class="data-row">
 <td>198</td>
 <td>2012-10-02</td>
 <td>56</td>
 <td>181</td>
 <td>7</td>
 <td>-73.0</td>
 <td>768.0</td>
 </tr>,
 <tr class="data-row">
 <td>199</td>
 <td>2012-10-03</td>
 <td>57</td>
 <td>181</td>
 <td>7</td>
 <td>-73.0</td>
 <td>769.0</td>
 </tr>,
 <tr class="data-row">
 <td>200</td>
 <td>2012-10-04</td>
 <td>58</td>
 <td>182</td>
 <td>7</td>
 <td>-74.0</td>
 <td>769.0</td>
 </tr>,
 <tr class="data-row">
 <td>201</td>
 <td>2012-10-05</td>
 <td>59</td>
 <td>183</td>
 <td>7</td>
 <td>-76.0</td>
 <td>771.0</td>
 </tr>,
 <tr class="data-row">
 <td>202</td>
 <td>2012-10-06</td>
 <td>60</td>
 <td>183</td>
 <td>7</td>
 <td>-75.0</td>
 <td>772.0</td>
 </tr>,
 <tr class="data-row">
 <td>203</td>
 <td>2012-10-07</td>
 <td>61</td>
 <td>184</td>
 <td>7</td>
 <td>-72.0</td>
 <td>772.0</td>
 </tr>,
 <tr class="data-row">
 <td>204</td>
 <td>2012-10-08</td>
 <td>62</td>
 <td>184</td>
 <td>7</td>
 <td>-72.0</td>
 <td>774.0</td>
 </tr>,
 <tr class="data-row">
 <td>205</td>
 <td>2012-10-09</td>
 <td>63</td>
 <td>185</td>
 <td>7</td>
 <td>-73.0</td>
 <td>775.0</td>
 </tr>,
 <tr class="data-row">
 <td>206</td>
 <td>2012-10-10</td>
 <td>64</td>
 <td>186</td>
 <td>7</td>
 <td>-74.0</td>
 <td>776.0</td>
 </tr>,
 <tr class="data-row">
 <td>207</td>
 <td>2012-10-11</td>
 <td>65</td>
 <td>186</td>
 <td>7</td>
 <td>-72.0</td>
 <td>777.0</td>
 </tr>,
 <tr class="data-row">
 <td>208</td>
 <td>2012-10-12</td>
 <td>66</td>
 <td>187</td>
 <td>7</td>
 <td>-73.0</td>
 <td>778.0</td>
 </tr>,
 <tr class="data-row">
 <td>209</td>
 <td>2012-10-13</td>
 <td>67</td>
 <td>187</td>
 <td>7</td>
 <td>-73.0</td>
 <td>780.0</td>
 </tr>,
 <tr class="data-row">
 <td>210</td>
 <td>2012-10-14</td>
 <td>68</td>
 <td>188</td>
 <td>7</td>
 <td>-71.0</td>
 <td>781.0</td>
 </tr>,
 <tr class="data-row">
 <td>211</td>
 <td>2012-10-15</td>
 <td>69</td>
 <td>189</td>
 <td>7</td>
 <td>-73.0</td>
 <td>778.0</td>
 </tr>,
 <tr class="data-row">
 <td>212</td>
 <td>2012-10-17</td>
 <td>70</td>
 <td>189</td>
 <td>7</td>
 <td>-72.0</td>
 <td>783.0</td>
 </tr>,
 <tr class="data-row">
 <td>213</td>
 <td>2012-10-18</td>
 <td>71</td>
 <td>190</td>
 <td>7</td>
 <td>-71.0</td>
 <td>784.0</td>
 </tr>,
 <tr class="data-row">
 <td>214</td>
 <td>2012-10-19</td>
 <td>72</td>
 <td>190</td>
 <td>7</td>
 <td>-73.0</td>
 <td>785.0</td>
 </tr>,
 <tr class="data-row">
 <td>215</td>
 <td>2012-10-20</td>
 <td>73</td>
 <td>191</td>
 <td>7</td>
 <td>-70.0</td>
 <td>788.0</td>
 </tr>,
 <tr class="data-row">
 <td>216</td>
 <td>2012-10-21</td>
 <td>74</td>
 <td>192</td>
 <td>7</td>
 <td>-72.0</td>
 <td>790.0</td>
 </tr>,
 <tr class="data-row">
 <td>217</td>
 <td>2012-10-22</td>
 <td>75</td>
 <td>192</td>
 <td>7</td>
 <td>-73.0</td>
 <td>791.0</td>
 </tr>,
 <tr class="data-row">
 <td>218</td>
 <td>2012-10-23</td>
 <td>76</td>
 <td>193</td>
 <td>7</td>
 <td>-73.0</td>
 <td>792.0</td>
 </tr>,
 <tr class="data-row">
 <td>219</td>
 <td>2012-10-24</td>
 <td>77</td>
 <td>193</td>
 <td>7</td>
 <td>-71.0</td>
 <td>792.0</td>
 </tr>,
 <tr class="data-row">
 <td>220</td>
 <td>2012-10-25</td>
 <td>78</td>
 <td>194</td>
 <td>7</td>
 <td>-71.0</td>
 <td>793.0</td>
 </tr>,
 <tr class="data-row">
 <td>221</td>
 <td>2012-10-26</td>
 <td>79</td>
 <td>195</td>
 <td>7</td>
 <td>-73.0</td>
 <td>795.0</td>
 </tr>,
 <tr class="data-row">
 <td>222</td>
 <td>2012-10-27</td>
 <td>80</td>
 <td>195</td>
 <td>7</td>
 <td>-70.0</td>
 <td>796.0</td>
 </tr>,
 <tr class="data-row">
 <td>223</td>
 <td>2012-10-28</td>
 <td>81</td>
 <td>196</td>
 <td>7</td>
 <td>-72.0</td>
 <td>798.0</td>
 </tr>,
 <tr class="data-row">
 <td>224</td>
 <td>2012-10-29</td>
 <td>82</td>
 <td>196</td>
 <td>7</td>
 <td>-72.0</td>
 <td>799.0</td>
 </tr>,
 <tr class="data-row">
 <td>225</td>
 <td>2012-10-30</td>
 <td>83</td>
 <td>197</td>
 <td>7</td>
 <td>-72.0</td>
 <td>801.0</td>
 </tr>,
 <tr class="data-row">
 <td>226</td>
 <td>2012-10-31</td>
 <td>84</td>
 <td>198</td>
 <td>7</td>
 <td>-70.0</td>
 <td>801.0</td>
 </tr>,
 <tr class="data-row">
 <td>227</td>
 <td>2012-11-01</td>
 <td>85</td>
 <td>198</td>
 <td>7</td>
 <td>-71.0</td>
 <td>805.0</td>
 </tr>,
 <tr class="data-row">
 <td>228</td>
 <td>2012-11-02</td>
 <td>86</td>
 <td>199</td>
 <td>7</td>
 <td>-71.0</td>
 <td>808.0</td>
 </tr>,
 <tr class="data-row">
 <td>229</td>
 <td>2012-11-03</td>
 <td>87</td>
 <td>199</td>
 <td>7</td>
 <td>-70.0</td>
 <td>808.0</td>
 </tr>,
 <tr class="data-row">
 <td>230</td>
 <td>2012-11-04</td>
 <td>88</td>
 <td>200</td>
 <td>7</td>
 <td>-70.0</td>
 <td>811.0</td>
 </tr>,
 <tr class="data-row">
 <td>231</td>
 <td>2012-11-05</td>
 <td>89</td>
 <td>201</td>
 <td>7</td>
 <td>-73.0</td>
 <td>813.0</td>
 </tr>,
 <tr class="data-row">
 <td>233</td>
 <td>2012-11-06</td>
 <td>90</td>
 <td>201</td>
 <td>7</td>
 <td>-71.0</td>
 <td>813.0</td>
 </tr>,
 <tr class="data-row">
 <td>234</td>
 <td>2012-11-07</td>
 <td>91</td>
 <td>202</td>
 <td>7</td>
 <td>-74.0</td>
 <td>817.0</td>
 </tr>,
 <tr class="data-row">
 <td>235</td>
 <td>2012-11-08</td>
 <td>92</td>
 <td>202</td>
 <td>7</td>
 <td>-74.0</td>
 <td>820.0</td>
 </tr>,
 <tr class="data-row">
 <td>236</td>
 <td>2012-11-09</td>
 <td>93</td>
 <td>203</td>
 <td>7</td>
 <td>-72.0</td>
 <td>819.0</td>
 </tr>,
 <tr class="data-row">
 <td>237</td>
 <td>2012-11-10</td>
 <td>94</td>
 <td>204</td>
 <td>7</td>
 <td>-70.0</td>
 <td>822.0</td>
 </tr>,
 <tr class="data-row">
 <td>238</td>
 <td>2012-11-11</td>
 <td>95</td>
 <td>204</td>
 <td>7</td>
 <td>-68.0</td>
 <td>822.0</td>
 </tr>,
 <tr class="data-row">
 <td>239</td>
 <td>2012-11-12</td>
 <td>96</td>
 <td>205</td>
 <td>7</td>
 <td>-71.0</td>
 <td>826.0</td>
 </tr>,
 <tr class="data-row">
 <td>240</td>
 <td>2012-11-13</td>
 <td>97</td>
 <td>206</td>
 <td>7</td>
 <td>-68.0</td>
 <td>828.0</td>
 </tr>,
 <tr class="data-row">
 <td>241</td>
 <td>2012-11-14</td>
 <td>98</td>
 <td>206</td>
 <td>7</td>
 <td>-68.0</td>
 <td>828.0</td>
 </tr>,
 <tr class="data-row">
 <td>242</td>
 <td>2012-11-15</td>
 <td>99</td>
 <td>207</td>
 <td>7</td>
 <td>-68.0</td>
 <td>829.0</td>
 </tr>,
 <tr class="data-row">
 <td>3</td>
 <td>2012-11-16</td>
 <td>100</td>
 <td>207</td>
 <td>7</td>
 <td>-66.0</td>
 <td>829.0</td>
 </tr>,
 <tr class="data-row">
 <td>4</td>
 <td>2012-11-17</td>
 <td>101</td>
 <td>208</td>
 <td>7</td>
 <td>-65.0</td>
 <td>830.0</td>
 </tr>,
 <tr class="data-row">
 <td>5</td>
 <td>2012-11-18</td>
 <td>102</td>
 <td>209</td>
 <td>7</td>
 <td>-67.0</td>
 <td>833.0</td>
 </tr>,
 <tr class="data-row">
 <td>6</td>
 <td>2012-11-19</td>
 <td>103</td>
 <td>209</td>
 <td>7</td>
 <td>-66.0</td>
 <td>836.0</td>
 </tr>,
 <tr class="data-row">
 <td>7</td>
 <td>2012-11-20</td>
 <td>104</td>
 <td>210</td>
 <td>8</td>
 <td>-67.0</td>
 <td>838.0</td>
 </tr>,
 <tr class="data-row">
 <td>8</td>
 <td>2012-11-21</td>
 <td>105</td>
 <td>211</td>
 <td>8</td>
 <td>-66.0</td>
 <td>839.0</td>
 </tr>,
 <tr class="data-row">
 <td>9</td>
 <td>2012-11-23</td>
 <td>106</td>
 <td>211</td>
 <td>8</td>
 <td>-66.0</td>
 <td>841.0</td>
 </tr>,
 <tr class="data-row">
 <td>10</td>
 <td>2012-11-24</td>
 <td>107</td>
 <td>212</td>
 <td>8</td>
 <td>-66.0</td>
 <td>844.0</td>
 </tr>,
 <tr class="data-row">
 <td>11</td>
 <td>2012-11-25</td>
 <td>108</td>
 <td>212</td>
 <td>8</td>
 <td>-65.0</td>
 <td>845.0</td>
 </tr>,
 <tr class="data-row">
 <td>12</td>
 <td>2012-11-26</td>
 <td>109</td>
 <td>213</td>
 <td>8</td>
 <td>-64.0</td>
 <td>844.0</td>
 </tr>,
 <tr class="data-row">
 <td>14</td>
 <td>2012-11-27</td>
 <td>110</td>
 <td>214</td>
 <td>8</td>
 <td>-65.0</td>
 <td>848.0</td>
 </tr>,
 <tr class="data-row">
 <td>15</td>
 <td>2012-11-28</td>
 <td>111</td>
 <td>214</td>
 <td>8</td>
 <td>-66.0</td>
 <td>849.0</td>
 </tr>,
 <tr class="data-row">
 <td>16</td>
 <td>2012-11-29</td>
 <td>112</td>
 <td>215</td>
 <td>8</td>
 <td>-65.0</td>
 <td>852.0</td>
 </tr>,
 <tr class="data-row">
 <td>17</td>
 <td>2012-11-30</td>
 <td>113</td>
 <td>216</td>
 <td>8</td>
 <td>-66.0</td>
 <td>857.0</td>
 </tr>,
 <tr class="data-row">
 <td>18</td>
 <td>2012-12-01</td>
 <td>114</td>
 <td>216</td>
 <td>8</td>
 <td>-69.0</td>
 <td>857.0</td>
 </tr>,
 <tr class="data-row">
 <td>19</td>
 <td>2012-12-02</td>
 <td>115</td>
 <td>217</td>
 <td>8</td>
 <td>-66.0</td>
 <td>857.0</td>
 </tr>,
 <tr class="data-row">
 <td>20</td>
 <td>2012-12-03</td>
 <td>116</td>
 <td>217</td>
 <td>8</td>
 <td>-67.0</td>
 <td>859.0</td>
 </tr>,
 <tr class="data-row">
 <td>21</td>
 <td>2012-12-04</td>
 <td>117</td>
 <td>218</td>
 <td>8</td>
 <td>-66.0</td>
 <td>861.0</td>
 </tr>,
 <tr class="data-row">
 <td>22</td>
 <td>2012-12-05</td>
 <td>118</td>
 <td>219</td>
 <td>8</td>
 <td>-65.0</td>
 <td>864.0</td>
 </tr>,
 <tr class="data-row">
 <td>23</td>
 <td>2012-12-06</td>
 <td>119</td>
 <td>219</td>
 <td>8</td>
 <td>-66.0</td>
 <td>866.0</td>
 </tr>,
 <tr class="data-row">
 <td>25</td>
 <td>2012-12-07</td>
 <td>120</td>
 <td>220</td>
 <td>8</td>
 <td>-67.0</td>
 <td>867.0</td>
 </tr>,
 <tr class="data-row">
 <td>26</td>
 <td>2012-12-08</td>
 <td>121</td>
 <td>221</td>
 <td>8</td>
 <td>-66.0</td>
 <td>869.0</td>
 </tr>,
 <tr class="data-row">
 <td>27</td>
 <td>2012-12-09</td>
 <td>122</td>
 <td>221</td>
 <td>8</td>
 <td>-65.0</td>
 <td>869.0</td>
 </tr>,
 <tr class="data-row">
 <td>28</td>
 <td>2012-12-10</td>
 <td>123</td>
 <td>222</td>
 <td>8</td>
 <td>-66.0</td>
 <td>875.0</td>
 </tr>,
 <tr class="data-row">
 <td>29</td>
 <td>2012-12-11</td>
 <td>124</td>
 <td>223</td>
 <td>8</td>
 <td>-66.0</td>
 <td>876.0</td>
 </tr>,
 <tr class="data-row">
 <td>30</td>
 <td>2012-12-12</td>
 <td>125</td>
 <td>223</td>
 <td>8</td>
 <td>-68.0</td>
 <td>880.0</td>
 </tr>,
 <tr class="data-row">
 <td>31</td>
 <td>2012-12-13</td>
 <td>126</td>
 <td>224</td>
 <td>8</td>
 <td>-66.0</td>
 <td>880.0</td>
 </tr>,
 <tr class="data-row">
 <td>32</td>
 <td>2012-12-14</td>
 <td>127</td>
 <td>224</td>
 <td>8</td>
 <td>-67.0</td>
 <td>884.0</td>
 </tr>,
 <tr class="data-row">
 <td>33</td>
 <td>2012-12-15</td>
 <td>128</td>
 <td>225</td>
 <td>8</td>
 <td>-67.0</td>
 <td>883.0</td>
 </tr>,
 <tr class="data-row">
 <td>34</td>
 <td>2012-12-16</td>
 <td>129</td>
 <td>226</td>
 <td>8</td>
 <td>-65.0</td>
 <td>886.0</td>
 </tr>,
 <tr class="data-row">
 <td>36</td>
 <td>2012-12-17</td>
 <td>130</td>
 <td>226</td>
 <td>8</td>
 <td>-65.0</td>
 <td>888.0</td>
 </tr>,
 <tr class="data-row">
 <td>37</td>
 <td>2012-12-18</td>
 <td>131</td>
 <td>227</td>
 <td>8</td>
 <td>-65.0</td>
 <td>889.0</td>
 </tr>,
 <tr class="data-row">
 <td>38</td>
 <td>2012-12-19</td>
 <td>132</td>
 <td>228</td>
 <td>8</td>
 <td>-65.0</td>
 <td>890.0</td>
 </tr>,
 <tr class="data-row">
 <td>39</td>
 <td>2012-12-20</td>
 <td>133</td>
 <td>228</td>
 <td>8</td>
 <td>-65.0</td>
 <td>891.0</td>
 </tr>,
 <tr class="data-row">
 <td>40</td>
 <td>2012-12-21</td>
 <td>134</td>
 <td>229</td>
 <td>8</td>
 <td>-67.0</td>
 <td>893.0</td>
 </tr>,
 <tr class="data-row">
 <td>41</td>
 <td>2012-12-22</td>
 <td>135</td>
 <td>230</td>
 <td>8</td>
 <td>-65.0</td>
 <td>894.0</td>
 </tr>,
 <tr class="data-row">
 <td>42</td>
 <td>2012-12-23</td>
 <td>136</td>
 <td>230</td>
 <td>8</td>
 <td>-65.0</td>
 <td>897.0</td>
 </tr>,
 <tr class="data-row">
 <td>43</td>
 <td>2012-12-24</td>
 <td>137</td>
 <td>231</td>
 <td>8</td>
 <td>-64.0</td>
 <td>896.0</td>
 </tr>,
 <tr class="data-row">
 <td>44</td>
 <td>2012-12-25</td>
 <td>138</td>
 <td>232</td>
 <td>8</td>
 <td>-65.0</td>
 <td>899.0</td>
 </tr>,
 <tr class="data-row">
 <td>45</td>
 <td>2012-12-26</td>
 <td>139</td>
 <td>232</td>
 <td>8</td>
 <td>-66.0</td>
 <td>899.0</td>
 </tr>,
 <tr class="data-row">
 <td>47</td>
 <td>2012-12-27</td>
 <td>140</td>
 <td>233</td>
 <td>8</td>
 <td>-66.0</td>
 <td>903.0</td>
 </tr>,
 <tr class="data-row">
 <td>48</td>
 <td>2012-12-28</td>
 <td>141</td>
 <td>233</td>
 <td>8</td>
 <td>-64.0</td>
 <td>904.0</td>
 </tr>,
 <tr class="data-row">
 <td>49</td>
 <td>2012-12-29</td>
 <td>142</td>
 <td>234</td>
 <td>8</td>
 <td>-65.0</td>
 <td>906.0</td>
 </tr>,
 <tr class="data-row">
 <td>50</td>
 <td>2012-12-31</td>
 <td>143</td>
 <td>235</td>
 <td>8</td>
 <td>-63.0</td>
 <td>908.0</td>
 </tr>,
 <tr class="data-row">
 <td>51</td>
 <td>2013-01-01</td>
 <td>144</td>
 <td>235</td>
 <td>8</td>
 <td>-64.0</td>
 <td>907.0</td>
 </tr>,
 <tr class="data-row">
 <td>52</td>
 <td>2013-01-02</td>
 <td>145</td>
 <td>236</td>
 <td>8</td>
 <td>-64.0</td>
 <td>909.0</td>
 </tr>,
 <tr class="data-row">
 <td>53</td>
 <td>2013-01-03</td>
 <td>146</td>
 <td>237</td>
 <td>8</td>
 <td>-65.0</td>
 <td>908.0</td>
 </tr>,
 <tr class="data-row">
 <td>54</td>
 <td>2013-01-04</td>
 <td>147</td>
 <td>237</td>
 <td>8</td>
 <td>-65.0</td>
 <td>914.0</td>
 </tr>,
 <tr class="data-row">
 <td>55</td>
 <td>2013-01-05</td>
 <td>148</td>
 <td>238</td>
 <td>8</td>
 <td>-65.0</td>
 <td>912.0</td>
 </tr>,
 <tr class="data-row">
 <td>56</td>
 <td>2013-01-06</td>
 <td>149</td>
 <td>239</td>
 <td>8</td>
 <td>-65.0</td>
 <td>914.0</td>
 </tr>,
 <tr class="data-row">
 <td>58</td>
 <td>2013-01-07</td>
 <td>150</td>
 <td>239</td>
 <td>8</td>
 <td>-64.0</td>
 <td>913.0</td>
 </tr>,
 <tr class="data-row">
 <td>59</td>
 <td>2013-01-08</td>
 <td>151</td>
 <td>240</td>
 <td>9</td>
 <td>-65.0</td>
 <td>915.0</td>
 </tr>,
 <tr class="data-row">
 <td>60</td>
 <td>2013-01-09</td>
 <td>152</td>
 <td>241</td>
 <td>9</td>
 <td>-63.0</td>
 <td>914.0</td>
 </tr>,
 <tr class="data-row">
 <td>61</td>
 <td>2013-01-10</td>
 <td>153</td>
 <td>241</td>
 <td>9</td>
 <td>-65.0</td>
 <td>915.0</td>
 </tr>,
 <tr class="data-row">
 <td>62</td>
 <td>2013-01-11</td>
 <td>154</td>
 <td>242</td>
 <td>9</td>
 <td>-65.0</td>
 <td>917.0</td>
 </tr>,
 <tr class="data-row">
 <td>63</td>
 <td>2013-01-12</td>
 <td>155</td>
 <td>243</td>
 <td>9</td>
 <td>-64.0</td>
 <td>917.0</td>
 </tr>,
 <tr class="data-row">
 <td>64</td>
 <td>2013-01-13</td>
 <td>156</td>
 <td>243</td>
 <td>9</td>
 <td>-65.0</td>
 <td>922.0</td>
 </tr>,
 <tr class="data-row">
 <td>65</td>
 <td>2013-01-14</td>
 <td>157</td>
 <td>244</td>
 <td>9</td>
 <td>-64.0</td>
 <td>920.0</td>
 </tr>,
 <tr class="data-row">
 <td>66</td>
 <td>2013-01-15</td>
 <td>158</td>
 <td>245</td>
 <td>9</td>
 <td>-66.0</td>
 <td>922.0</td>
 </tr>,

### Step 3: Store the Data

Assemble the scraped data into a Pandas DataFrame. The columns should have the same headings as the table on the website. Here’s an explanation of the column headings:

* `id`: the identification number of a single transmission from the Curiosity rover
* `terrestrial_date`: the date on Earth
* `sol`: the number of elapsed sols (Martian days) since Curiosity landed on Mars
* `ls`: the solar longitude
* `month`: the Martian month
* `min_temp`: the minimum temperature, in Celsius, of a single Martian day (sol)
* `pressure`: The atmospheric pressure at Curiosity's location

In [29]:
# Create an empty list
climate_list = []

# Loop through the scraped data to create a list of rows
for row in data_rows:
    climate_list.append(row.text.strip().split(':'))

climate_list

[['id\nterrestrial_date\nsol\nls\nmonth\nmin_temp\npressure'],
 ['2\n2012-08-16\n10\n155\n6\n-75.0\n739.0'],
 ['13\n2012-08-17\n11\n156\n6\n-76.0\n740.0'],
 ['24\n2012-08-18\n12\n156\n6\n-76.0\n741.0'],
 ['35\n2012-08-19\n13\n157\n6\n-74.0\n732.0'],
 ['46\n2012-08-20\n14\n157\n6\n-74.0\n740.0'],
 ['57\n2012-08-21\n15\n158\n6\n-78.0\n740.0'],
 ['68\n2012-08-22\n16\n158\n6\n-77.0\n740.0'],
 ['79\n2012-08-23\n17\n159\n6\n-76.0\n742.0'],
 ['112\n2012-08-27\n21\n161\n6\n-74.0\n741.0'],
 ['114\n2012-08-28\n22\n162\n6\n-74.0\n742.0'],
 ['123\n2012-08-29\n23\n162\n6\n-75.0\n741.0'],
 ['134\n2012-08-30\n24\n163\n6\n-75.0\n742.0'],
 ['145\n2012-08-31\n25\n163\n6\n-75.0\n743.0'],
 ['156\n2012-09-01\n26\n164\n6\n-76.0\n745.0'],
 ['163\n2012-09-02\n27\n164\n6\n-75.0\n743.0'],
 ['170\n2012-09-03\n28\n165\n6\n-75.0\n745.0'],
 ['171\n2012-09-04\n29\n166\n6\n-75.0\n747.0'],
 ['172\n2012-09-05\n30\n166\n6\n-74.0\n747.0'],
 ['173\n2012-09-06\n31\n167\n6\n-74.0\n745.0'],
 ['175\n2012-09-08\n33\n168\n6\n-73.0\n748.0'],
 ['176\n2012-09-10\n34\n168\n6\n-73.0\n748.0'],
 ['177\n2012-09-11\n35\n169\n6\n-73.0\n749.0'],
 ['178\n2012-09-12\n36\n169\n6\n-73.0\n750.0'],
 ['179\n2012-09-13\n37\n170\n6\n-73.0\n750.0'],
 ['180\n2012-09-14\n38\n171\n6\n-73.0\n750.0'],
 ['181\n2012-09-15\n39\n171\n6\n-75.0\n751.0'],
 ['182\n2012-09-16\n40\n172\n6\n-75.0\n753.0'],
 ['183\n2012-09-17\n41\n172\n6\n-75.0\n753.0'],
 ['184\n2012-09-18\n42\n173\n6\n-75.0\n754.0'],
 ['185\n2012-09-19\n43\n173\n6\n-74.0\n756.0'],
 ['186\n2012-09-20\n44\n174\n6\n-75.0\n757.0'],
 ['187\n2012-09-21\n45\n175\n6\n-74.0\n758.0'],
 ['188\n2012-09-22\n46\n175\n6\n-74.0\n758.0'],
 ['189\n2012-09-23\n47\n176\n6\n-75.0\n758.0'],
 ['190\n2012-09-24\n48\n176\n6\n-75.0\n759.0'],
 ['191\n2012-09-25\n49\n177\n6\n-74.0\n761.0'],
 ['192\n2012-09-26\n50\n177\n6\n-72.0\n761.0'],
 ['193\n2012-09-27\n51\n178\n6\n-76.0\n762.0'],
 ['194\n2012-09-28\n52\n179\n6\n-74.0\n762.0'],
 ['195\n2012-09-29\n53\n179\n6\n-71.0\n764.0'],
 ['196\n2012-09-30\n54\n180\n7\n-72.0\n766.0'],
 ['197\n2012-10-01\n55\n180\n7\n-74.0\n766.0'],
 ['198\n2012-10-02\n56\n181\n7\n-73.0\n768.0'],
 ['199\n2012-10-03\n57\n181\n7\n-73.0\n769.0'],
 ['200\n2012-10-04\n58\n182\n7\n-74.0\n769.0'],
 ['201\n2012-10-05\n59\n183\n7\n-76.0\n771.0'],
 ['202\n2012-10-06\n60\n183\n7\n-75.0\n772.0'],
 ['203\n2012-10-07\n61\n184\n7\n-72.0\n772.0'],
 ['204\n2012-10-08\n62\n184\n7\n-72.0\n774.0'],
 ['205\n2012-10-09\n63\n185\n7\n-73.0\n775.0'],
 ['206\n2012-10-10\n64\n186\n7\n-74.0\n776.0'],
 ['207\n2012-10-11\n65\n186\n7\n-72.0\n777.0'],
 ['208\n2012-10-12\n66\n187\n7\n-73.0\n778.0'],
 ['209\n2012-10-13\n67\n187\n7\n-73.0\n780.0'],
 ['210\n2012-10-14\n68\n188\n7\n-71.0\n781.0'],
 ['211\n2012-10-15\n69\n189\n7\n-73.0\n778.0'],
 ['212\n2012-10-17\n70\n189\n7\n-72.0\n783.0'],
 ['213\n2012-10-18\n71\n190\n7\n-71.0\n784.0'],
 ['214\n2012-10-19\n72\n190\n7\n-73.0\n785.0'],
 ['215\n2012-10-20\n73\n191\n7\n-70.0\n788.0'],
 ['216\n2012-10-21\n74\n192\n7\n-72.0\n790.0'],
 ['217\n2012-10-22\n75\n192\n7\n-73.0\n791.0'],
 ['218\n2012-10-23\n76\n193\n7\n-73.0\n792.0'],
 ['219\n2012-10-24\n77\n193\n7\n-71.0\n792.0'],
 ['220\n2012-10-25\n78\n194\n7\n-71.0\n793.0'],
 ['221\n2012-10-26\n79\n195\n7\n-73.0\n795.0'],
 ['222\n2012-10-27\n80\n195\n7\n-70.0\n796.0'],
 ['223\n2012-10-28\n81\n196\n7\n-72.0\n798.0'],
 ['224\n2012-10-29\n82\n196\n7\n-72.0\n799.0'],
 ['225\n2012-10-30\n83\n197\n7\n-72.0\n801.0'],
 ['226\n2012-10-31\n84\n198\n7\n-70.0\n801.0'],
 ['227\n2012-11-01\n85\n198\n7\n-71.0\n805.0'],
 ['228\n2012-11-02\n86\n199\n7\n-71.0\n808.0'],
 ['229\n2012-11-03\n87\n199\n7\n-70.0\n808.0'],
 ['230\n2012-11-04\n88\n200\n7\n-70.0\n811.0'],
 ['231\n2012-11-05\n89\n201\n7\n-73.0\n813.0'],
 ['233\n2012-11-06\n90\n201\n7\n-71.0\n813.0'],
 ['234\n2012-11-07\n91\n202\n7\n-74.0\n817.0'],
 ['235\n2012-11-08\n92\n202\n7\n-74.0\n820.0'],
 ['236\n2012-11-09\n93\n203\n7\n-72.0\n819.0'],
 ['237\n2012-11-10\n94\n204\n7\n-70.0\n822.0'],
 ['238\n2012-11-11\n95\n204\n7\n-68.0\n822.0'],
 ['239\n2012-11-12\n96\n205\n7\n-71.0\n826.0'],
 ['240\n2012-11-13\n97\n206\n7\n-68.0\n828.0'],
 ['241\n2012-11-14\n98\n206\n7\n-68.0\n828.0'],
 ['242\n2012-11-15\n99\n207\n7\n-68.0\n829.0'],
 ['3\n2012-11-16\n100\n207\n7\n-66.0\n829.0'],
 ['4\n2012-11-17\n101\n208\n7\n-65.0\n830.0'],
 ['5\n2012-11-18\n102\n209\n7\n-67.0\n833.0'],
 ['6\n2012-11-19\n103\n209\n7\n-66.0\n836.0'],
 ['7\n2012-11-20\n104\n210\n8\n-67.0\n838.0'],
 ['8\n2012-11-21\n105\n211\n8\n-66.0\n839.0'],
 ['9\n2012-11-23\n106\n211\n8\n-66.0\n841.0'],
 ['10\n2012-11-24\n107\n212\n8\n-66.0\n844.0'],
 ['11\n2012-11-25\n108\n212\n8\n-65.0\n845.0'],
 ['12\n2012-11-26\n109\n213\n8\n-64.0\n844.0'],
 ['14\n2012-11-27\n110\n214\n8\n-65.0\n848.0'],
 ['15\n2012-11-28\n111\n214\n8\n-66.0\n849.0'],
 ['16\n2012-11-29\n112\n215\n8\n-65.0\n852.0'],
 ['17\n2012-11-30\n113\n216\n8\n-66.0\n857.0'],
 ['18\n2012-12-01\n114\n216\n8\n-69.0\n857.0'],
 ['19\n2012-12-02\n115\n217\n8\n-66.0\n857.0'],
 ['20\n2012-12-03\n116\n217\n8\n-67.0\n859.0'],
 ['21\n2012-12-04\n117\n218\n8\n-66.0\n861.0'],
 ['22\n2012-12-05\n118\n219\n8\n-65.0\n864.0'],
 ['23\n2012-12-06\n119\n219\n8\n-66.0\n866.0'],
 ['25\n2012-12-07\n120\n220\n8\n-67.0\n867.0'],
 ['26\n2012-12-08\n121\n221\n8\n-66.0\n869.0'],
 ['27\n2012-12-09\n122\n221\n8\n-65.0\n869.0'],
 ['28\n2012-12-10\n123\n222\n8\n-66.0\n875.0'],
 ['29\n2012-12-11\n124\n223\n8\n-66.0\n876.0'],
 ['30\n2012-12-12\n125\n223\n8\n-68.0\n880.0'],
 ['31\n2012-12-13\n126\n224\n8\n-66.0\n880.0'],
 ['32\n2012-12-14\n127\n224\n8\n-67.0\n884.0'],
 ['33\n2012-12-15\n128\n225\n8\n-67.0\n883.0'],
 ['34\n2012-12-16\n129\n226\n8\n-65.0\n886.0'],
 ['36\n2012-12-17\n130\n226\n8\n-65.0\n888.0'],
 ['37\n2012-12-18\n131\n227\n8\n-65.0\n889.0'],
 ['38\n2012-12-19\n132\n228\n8\n-65.0\n890.0'],
 ['39\n2012-12-20\n133\n228\n8\n-65.0\n891.0'],
 ['40\n2012-12-21\n134\n229\n8\n-67.0\n893.0'],
 ['41\n2012-12-22\n135\n230\n8\n-65.0\n894.0'],
 ['42\n2012-12-23\n136\n230\n8\n-65.0\n897.0'],
 ['43\n2012-12-24\n137\n231\n8\n-64.0\n896.0'],
 ['44\n2012-12-25\n138\n232\n8\n-65.0\n899.0'],
 ['45\n2012-12-26\n139\n232\n8\n-66.0\n899.0'],
 ['47\n2012-12-27\n140\n233\n8\n-66.0\n903.0'],
 ['48\n2012-12-28\n141\n233\n8\n-64.0\n904.0'],
 ['49\n2012-12-29\n142\n234\n8\n-65.0\n906.0'],
 ['50\n2012-12-31\n143\n235\n8\n-63.0\n908.0'],
 ['51\n2013-01-01\n144\n235\n8\n-64.0\n907.0'],
 ['52\n2013-01-02\n145\n236\n8\n-64.0\n909.0'],
 ['53\n2013-01-03\n146\n237\n8\n-65.0\n908.0'],
 ['54\n2013-01-04\n147\n237\n8\n-65.0\n914.0'],
 ['55\n2013-01-05\n148\n238\n8\n-65.0\n912.0'],
 ['56\n2013-01-06\n149\n239\n8\n-65.0\n914.0'],
 ['58\n2013-01-07\n150\n239\n8\n-64.0\n913.0'],
 ['59\n2013-01-08\n151\n240\n9\n-65.0\n915.0'],
 ['60\n2013-01-09\n152\n241\n9\n-63.0\n914.0'],
 ['61\n2013-01-10\n153\n241\n9\n-65.0\n915.0'],
 ['62\n2013-01-11\n154\n242\n9\n-65.0\n917.0'],
 ['63\n2013-01-12\n155\n243\n9\n-64.0\n917.0'],
 ['64\n2013-01-13\n156\n243\n9\n-65.0\n922.0'],
 ['65\n2013-01-14\n157\n244\n9\n-64.0\n920.0'],
 ['66\n2013-01-15\n158\n245\n9\n-66.0\n922.0'],
 ['67\n2013-01-16\n159\n245\n9\n-65.0\n918.0'],
 ['69\n2013-01-17\n160\n246\n9\n-67.0\n919.0'],
 ['70\n2013-01-18\n161\n246\n9\n-65.0\n919.0'],
 ['71\n2013-01-19\n162\n247\n9\n-65.0\n919.0'],
 ['72\n2013-01-20\n163\n248\n9\n-65.0\n919.0'],
 ['73\n2013-01-21\n164\n248\n9\n-64.0\n919.0'],
 ['74\n2013-01-22\n165\n249\n9\n-65.0\n922.0'],
 ['75\n2013-01-23\n166\n250\n9\n-65.0\n922.0'],
 ['76\n2013-01-24\n167\n250\n9\n-65.0\n920.0'],
 ['77\n2013-01-25\n168\n251\n9\n-66.0\n923.0'],
 ['78\n2013-01-26\n169\n252\n9\n-66.0\n922.0'],
 ['80\n2013-01-27\n170\n252\n9\n-66.0\n925.0'],
 ['81\n2013-01-28\n171\n253\n9\n-67.0\n925.0'],
 ['82\n2013-01-29\n172\n254\n9\n-67.0\n923.0'],
 ['83\n2013-01-30\n173\n254\n9\n-67.0\n920.0'],
 ['84\n2013-01-31\n174\n255\n9\n-67.0\n921.0'],
 ['85\n2013-02-01\n175\n256\n9\n-68.0\n921.0'],
 ['86\n2013-02-02\n176\n256\n9\n-67.0\n920.0'],
 ['87\n2013-02-03\n177\n257\n9\n-66.0\n921.0'],
 ['88\n2013-02-04\n178\n258\n9\n-66.0\n920.0'],
 ['89\n2013-02-06\n179\n258\n9\n-66.0\n920.0'],
 ['91\n2013-02-07\n180\n259\n9\n-67.0\n919.0'],
 ['92\n2013-02-08\n181\n260\n9\n-67.0\n918.0'],
 ['93\n2013-02-09\n182\n260\n9\n-67.0\n921.0'],
 ['94\n2013-02-10\n183\n261\n9\n-67.0\n921.0'],
 ['95\n2013-02-11\n184\n261\n9\n-67.0\n923.0'],
 ['96\n2013-02-12\n185\n262\n9\n-67.0\n923.0'],
 ['97\n2013-02-13\n186\n263\n9\n-66.0\n922.0'],
 ['98\n2013-02-14\n187\n263\n9\n-67.0\n921.0'],
 ['99\n2013-02-15\n188\n264\n9\n-68.0\n920.0'],
 ['100\n2013-02-16\n189\n265\n9\n-68.0\n920.0'],
 ['102\n2013-02-17\n190\n265\n9\n-66.0\n917.0'],
 ['103\n2013-02-18\n191\n266\n9\n-67.0\n921.0'],
 ['106\n2013-02-23\n196\n269\n9\n-66.0\n916.0'],
 ['107\n2013-02-24\n197\n270\n10\n-68.0\n915.0'],
 ['108\n2013-02-25\n198\n271\n10\n-67.0\n914.0'],
 ['109\n2013-02-26\n199\n271\n10\n-66.0\n917.0'],
 ['116\n2013-03-23\n223\n287\n10\n-71.0\n895.0'],
 ['117\n2013-03-24\n224\n287\n10\n-69.0\n894.0'],
 ['118\n2013-03-25\n225\n288\n10\n-71.0\n894.0'],
 ['119\n2013-03-26\n226\n288\n10\n-70.0\n894.0'],
 ['120\n2013-03-27\n227\n289\n10\n-70.0\n892.0'],
 ['121\n2013-03-28\n228\n290\n10\n-71.0\n894.0'],
 ['122\n2013-03-29\n229\n290\n10\n-69.0\n894.0'],
 ['124\n2013-03-30\n230\n291\n10\n-69.0\n888.0'],
 ['125\n2013-03-31\n231\n292\n10\n-71.0\n890.0'],
 ['126\n2013-04-01\n232\n292\n10\n-69.0\n888.0'],
 ['127\n2013-04-02\n233\n293\n10\n-69.0\n889.0'],
 ['128\n2013-04-03\n234\n293\n10\n-69.0\n890.0'],
 ['129\n2013-04-04\n235\n294\n10\n-70.0\n886.0'],
 ['130\n2013-04-05\n236\n295\n10\n-72.0\n886.0'],
 ['131\n2013-04-06\n237\n295\n10\n-71.0\n883.0'],
 ['132\n2013-04-07\n238\n296\n10\n-70.0\n885.0'],
 ['133\n2013-04-08\n239\n297\n10\n-73.0\n885.0'],
 ['135\n2013-04-09\n240\n297\n10\n-70.0\n884.0'],
 ['136\n2013-04-10\n241\n298\n10\n-72.0\n884.0'],
 ['137\n2013-04-11\n242\n298\n10\n-70.0\n881.0'],
 ['138\n2013-04-12\n243\n299\n10\n-71.0\n884.0'],
 ['139\n2013-04-13\n244\n300\n11\n-69.0\n878.0'],
 ['140\n2013-04-14\n245\n300\n11\n-70.0\n879.0'],
 ['141\n2013-04-15\n246\n301\n11\n-73.0\n878.0'],
 ['142\n2013-04-16\n247\n301\n11\n-71.0\n873.0'],
 ['143\n2013-04-17\n248\n302\n11\n-70.0\n877.0'],
 ['144\n2013-04-18\n249\n303\n11\n-69.0\n873.0'],
 ['146\n2013-04-19\n250\n303\n11\n-70.0\n877.0'],
 ['147\n2013-04-20\n251\n304\n11\n-71.0\n876.0'],
 ['148\n2013-04-22\n252\n304\n11\n-71.0\n874.0'],
 ['149\n2013-04-23\n253\n305\n11\n-71.0\n877.0'],
 ['150\n2013-04-24\n254\n306\n11\n-70.0\n871.0'],
 ['151\n2013-04-25\n255\n306\n11\n-69.0\n877.0'],
 ['152\n2013-04-26\n256\n307\n11\n-70.0\n871.0'],
 ['153\n2013-04-27\n257\n308\n11\n-70.0\n871.0'],
 ['154\n2013-04-28\n258\n308\n11\n-71.0\n869.0'],
 ['155\n2013-04-29\n259\n309\n11\n-72.0\n871.0'],
 ['157\n2013-04-30\n260\n309\n11\n-70.0\n875.0'],
 ['158\n2013-05-01\n261\n310\n11\n-70.0\n868.0'],
 ['161\n2013-05-08\n268\n314\n11\n-70.0\n864.0'],
 ['162\n2013-05-09\n269\n315\n11\n-72.0\n866.0'],
 ['164\n2013-05-10\n270\n315\n11\n-67.0\n863.0'],
 ['165\n2013-05-11\n271\n316\n11\n-69.0\n864.0'],
 ['166\n2013-05-12\n272\n316\n11\n-71.0\n864.0'],
 ['167\n2013-05-13\n273\n317\n11\n-70.0\n861.0'],
 ['168\n2013-05-14\n274\n318\n11\n-70.0\n861.0'],
 ['169\n2013-05-15\n275\n318\n11\n-67.0\n860.0'],
 ['244\n2013-05-16\n276\n319\n11\n-69.0\n858.0'],
 ['245\n2013-05-17\n277\n319\n11\n-69.0\n857.0'],
 ['246\n2013-05-18\n278\n320\n11\n-67.0\n855.0'],
 ['247\n2013-05-19\n279\n321\n11\n-68.0\n856.0'],
 ['248\n2013-05-20\n280\n321\n11\n-69.0\n856.0'],
 ['249\n2013-05-21\n281\n322\n11\n-68.0\n855.0'],
 ['250\n2013-05-22\n282\n322\n11\n-72.0\n856.0'],
 ['251\n2013-05-23\n283\n323\n11\n-68.0\n854.0'],
 ['252\n2013-05-24\n284\n323\n11\n-71.0\n854.0'],
 ['253\n2013-05-25\n285\n324\n11\n-70.0\n852.0'],
 ['254\n2013-05-26\n286\n325\n11\n-71.0\n854.0'],
 ['255\n2013-05-27\n287\n325\n11\n-72.0\n856.0'],
 ['256\n2013-05-29\n288\n326\n11\n-69.0\n854.0'],
 ['257\n2013-05-30\n289\n326\n11\n-71.0\n854.0'],
 ['258\n2013-05-31\n290\n327\n11\n-71.0\n853.0'],
 ['259\n2013-06-01\n291\n327\n11\n-70.0\n853.0'],
 ['260\n2013-06-02\n292\n328\n11\n-71.0\n853.0'],
 ['261\n2013-06-03\n293\n329\n11\n-72.0\n850.0'],
 ['262\n2013-06-04\n294\n329\n11\n-72.0\n852.0'],
 ['263\n2013-06-05\n295\n330\n12\n-71.0\n853.0'],
 ['264\n2013-06-06\n296\n330\n12\n-71.0\n850.0'],
 ['265\n2013-06-07\n297\n331\n12\n-72.0\n849.0'],
 ['266\n2013-06-08\n298\n331\n12\n-72.0\n850.0'],
 ['267\n2013-06-09\n299\n332\n12\n-71.0\n849.0'],
 ['286\n2013-06-10\n300\n333\n12\n-72.0\n852.0'],
 ['276\n2013-06-11\n301\n333\n12\n-73.0\n852.0'],
 ['287\n2013-06-12\n302\n334\n12\n-71.0\n850.0'],
 ['283\n2013-06-13\n303\n334\n12\n-71.0\n849.0'],
 ['281\n2013-06-14\n304\n335\n12\n-70.0\n848.0'],
 ['275\n2013-06-15\n305\n335\n12\n-71.0\n847.0'],
 ['280\n2013-06-16\n306\n336\n12\n-71.0\n848.0'],
 ['279\n2013-06-17\n307\n336\n12\n-72.0\n851.0'],
 ['282\n2013-06-18\n308\n337\n12\n-73.0\n850.0'],
 ['284\n2013-06-19\n309\n338\n12\n-72.0\n848.0'],
 ['278\n2013-06-20\n310\n338\n12\n-71.0\n849.0'],
 ['277\n2013-06-21\n311\n339\n12\n-74.0\n846.0'],
 ['285\n2013-06-22\n312\n339\n12\n-71.0\n845.0'],
 ['274\n2013-06-23\n313\n340\n12\n-77.0\n849.0'],
 ['272\n2013-06-24\n314\n340\n12\n-73.0\n848.0'],
 ['273\n2013-06-25\n315\n341\n12\n-74.0\n850.0'],
 ['288\n2013-06-26\n316\n341\n12\n-74.0\n851.0'],
 ['268\n2013-06-27\n317\n342\n12\n-72.0\n849.0'],
 ['270\n2013-06-28\n318\n342\n12\n-74.0\n849.0'],
 ['271\n2013-06-29\n319\n343\n12\n-73.0\n847.0'],
 ['269\n2013-06-30\n320\n344\n12\n-74.0\n846.0'],
 ['289\n2013-07-01\n321\n344\n12\n-75.0\n847.0'],
 ['291\n2013-07-02\n322\n345\n12\n-74.0\n849.0'],
 ['290\n2013-07-03\n323\n345\n12\n-74.0\n847.0'],
 ['292\n2013-07-04\n324\n346\n12\n-75.0\n850.0'],
 ['294\n2013-07-06\n325\n346\n12\n-74.0\n847.0'],
 ['295\n2013-07-07\n326\n347\n12\n-72.0\n848.0'],
 ['296\n2013-07-08\n327\n347\n12\n-74.0\n848.0'],
 ['293\n2013-07-09\n328\n348\n12\n-75.0\n847.0'],
 ['298\n2013-07-10\n329\n348\n12\n-74.0\n847.0'],
 ['297\n2013-07-11\n330\n349\n12\n-75.0\n848.0'],
 ['303\n2013-07-12\n331\n349\n12\n-74.0\n848.0'],
 ['300\n2013-07-13\n332\n350\n12\n-76.0\n849.0'],
 ['299\n2013-07-14\n333\n350\n12\n-75.0\n849.0'],
 ['301\n2013-07-15\n334\n351\n12\n-74.0\n852.0'],
 ['302\n2013-07-16\n335\n352\n12\n-76.0\n852.0'],
 ['305\n2013-07-17\n336\n352\n12\n-76.0\n852.0'],
 ['304\n2013-07-18\n337\n353\n12\n-75.0\n853.0'],
 ['306\n2013-07-19\n338\n353\n12\n-78.0\n848.0'],
 ['308\n2013-07-20\n339\n354\n12\n-76.0\n849.0'],
 ['307\n2013-07-21\n340\n354\n12\n-76.0\n851.0'],
 ['310\n2013-07-22\n341\n355\n12\n-77.0\n852.0'],
 ['309\n2013-07-23\n342\n355\n12\n-76.0\n851.0'],
 ['311\n2013-07-24\n343\n356\n12\n-77.0\n850.0'],
 ['317\n2013-07-25\n344\n356\n12\n-77.0\n851.0'],
 ['312\n2013-07-26\n345\n357\n12\n-77.0\n853.0'],
 ['314\n2013-07-27\n346\n357\n12\n-76.0\n853.0'],
 ['313\n2013-07-28\n347\n358\n12\n-77.0\n851.0'],
 ['315\n2013-07-29\n348\n358\n12\n-74.0\n850.0'],
 ['316\n2013-07-30\n349\n359\n12\n-75.0\n852.0'],
 ['318\n2013-07-31\n350\n359\n12\n-76.0\n853.0'],
 ['320\n2013-08-01\n351\n0\n1\n-75.0\n853.0'],
 ['319\n2013-08-02\n352\n0\n1\n-77.0\n854.0'],
 ['323\n2013-08-03\n353\n1\n1\n-75.0\n855.0'],
 ['322\n2013-08-04\n354\n1\n1\n-75.0\n857.0'],
 ['321\n2013-08-05\n355\n2\n1\n-75.0\n857.0'],
 ['324\n2013-08-06\n356\n2\n1\n-77.0\n856.0'],
 ['325\n2013-08-07\n357\n3\n1\n-76.0\n857.0'],
 ['326\n2013-08-17\n366\n7\n1\n-76.0\n861.0'],
 ['328\n2013-08-18\n367\n8\n1\n-76.0\n862.0'],
 ['330\n2013-08-19\n368\n8\n1\n-77.0\n863.0'],
 ['331\n2013-08-20\n369\n9\n1\n-75.0\n865.0'],
 ['332\n2013-08-21\n370\n9\n1\n-79.0\n865.0'],
 ['333\n2013-08-22\n371\n10\n1\n-77.0\n865.0'],
 ['334\n2013-08-23\n372\n10\n1\n-76.0\n866.0'],
 ['335\n2013-08-24\n373\n11\n1\n-79.0\n866.0'],
 ['337\n2013-08-25\n374\n11\n1\n-79.0\n866.0'],
 ['336\n2013-08-26\n375\n12\n1\n-77.0\n867.0'],
 ['340\n2013-08-27\n376\n12\n1\n-78.0\n870.0'],
 ['338\n2013-08-28\n377\n13\n1\n-78.0\n870.0'],
 ['339\n2013-08-29\n378\n13\n1\n-78.0\n869.0'],
 ['341\n2013-08-30\n379\n14\n1\n-79.0\n870.0'],
 ['343\n2013-08-31\n380\n14\n1\n-79.0\n870.0'],
 ['345\n2013-09-01\n381\n15\n1\n-79.0\n871.0'],
 ['344\n2013-09-02\n382\n15\n1\n-76.0\n872.0'],
 ['342\n2013-09-03\n383\n16\n1\n-77.0\n874.0'],
 ['346\n2013-09-04\n384\n16\n1\n-77.0\n875.0'],
 ['351\n2013-09-05\n385\n17\n1\n-78.0\n874.0'],
 ['347\n2013-09-06\n386\n17\n1\n-77.0\n873.0'],
 ['349\n2013-09-07\n387\n18\n1\n-78.0\n874.0'],
 ['350\n2013-09-08\n388\n18\n1\n-79.0\n875.0'],
 ['348\n2013-09-09\n389\n19\n1\n-79.0\n875.0'],
 ['352\n2013-09-10\n390\n19\n1\n-78.0\n875.0'],
 ['353\n2013-09-11\n391\n20\n1\n-78.0\n875.0'],
 ['354\n2013-09-12\n392\n20\n1\n-77.0\n876.0'],
 ['355\n2013-09-13\n393\n21\n1\n-76.0\n877.0'],
 ['356\n2013-09-14\n394\n21\n1\n-79.0\n878.0'],
 ['357\n2013-09-15\n395\n22\n1\n-77.0\n878.0'],
 ['358\n2013-09-16\n396\n22\n1\n-78.0\n879.0'],
 ['359\n2013-09-18\n397\n23\n1\n-75.0\n880.0'],
 ['360\n2013-09-19\n398\n23\n1\n-79.0\n880.0'],
 ['361\n2013-09-20\n399\n24\n1\n-79.0\n881.0'],
 ['363\n2013-09-21\n400\n24\n1\n-79.0\n881.0'],
 ['362\n2013-09-22\n401\n25\n1\n-79.0\n882.0'],
 ['365\n2013-09-23\n402\n25\n1\n-78.0\n883.0'],
 ['364\n2013-09-24\n403\n25\n1\n-80.0\n883.0'],
 ['367\n2013-09-25\n404\n26\n1\n-78.0\n884.0'],
 ['366\n2013-09-26\n405\n26\n1\n-82.0\n885.0'],
 ['374\n2013-09-27\n406\n27\n1\n-81.0\n886.0'],
 ['370\n2013-09-28\n407\n27\n1\n-81.0\n887.0'],
 ['369\n2013-09-29\n408\n28\n1\n-80.0\n887.0'],
 ['368\n2013-09-30\n409\n28\n1\n-81.0\n887.0'],
 ['373\n2013-10-01\n410\n29\n1\n-81.0\n888.0'],
 ['372\n2013-10-02\n411\n29\n1\n-82.0\n887.0'],
 ['371\n2013-10-03\n412\n30\n2\n-80.0\n888.0'],
 ['376\n2013-10-04\n413\n30\n2\n-82.0\n888.0'],
 ['375\n2013-10-05\n414\n31\n2\n-79.0\n889.0'],
 ['377\n2013-10-06\n415\n31\n2\n-82.0\n890.0'],
 ['378\n2013-10-07\n416\n32\n2\n-79.0\n889.0'],
 ['379\n2013-10-08\n417\n32\n2\n-82.0\n890.0'],
 ['380\n2013-10-09\n418\n33\n2\n-79.0\n891.0'],
 ['381\n2013-10-10\n419\n33\n2\n-82.0\n891.0'],
 ['385\n2013-10-11\n420\n33\n2\n-80.0\n892.0'],
 ['382\n2013-10-12\n421\n34\n2\n-81.0\n890.0'],
 ['384\n2013-10-13\n422\n34\n2\n-82.0\n891.0'],
 ['383\n2013-10-14\n423\n35\n2\n-81.0\n892.0'],
 ['386\n2013-10-15\n424\n35\n2\n-81.0\n893.0'],
 ['393\n2013-10-16\n425\n36\n2\n-81.0\n893.0'],
 ['388\n2013-10-17\n426\n36\n2\n-79.0\n893.0'],
 ['392\n2013-10-18\n427\n37\n2\n-81.0\n893.0'],
 ['391\n2013-10-19\n428\n37\n2\n-81.0\n894.0'],
 ['387\n2013-10-20\n429\n38\n2\n-82.0\n895.0'],
 ['390\n2013-10-21\n430\n38\n2\n-82.0\n896.0'],
 ['389\n2013-10-22\n431\n39\n2\n-83.0\n895.0'],
 ['395\n2013-10-23\n432\n39\n2\n-80.0\n896.0'],
 ['394\n2013-10-24\n433\n40\n2\n-81.0\n895.0'],
 ['397\n2013-10-26\n434\n40\n2\n-80.0\n896.0'],
 ['396\n2013-10-27\n435\n40\n2\n-81.0\n896.0'],
 ['398\n2013-10-28\n436\n41\n2\n-81.0\n897.0'],
 ['399\n2013-10-29\n437\n41\n2\n-82.0\n898.0'],
 ['400\n2013-10-30\n438\n42\n2\n-79.0\n899.0'],
 ['401\n2013-10-31\n439\n42\n2\n-80.0\n899.0'],
 ['404\n2013-11-01\n440\n43\n2\n-80.0\n899.0'],
 ['402\n2013-11-02\n441\n43\n2\n-81.0\n900.0'],
 ['405\n2013-11-03\n442\n44\n2\n-80.0\n900.0'],
 ['403\n2013-11-04\n443\n44\n2\n-81.0\n901.0'],
 ['407\n2013-11-16\n455\n50\n2\n-84.0\n905.0'],
 ['406\n2013-11-17\n456\n50\n2\n-83.0\n905.0'],
 ['409\n2013-11-24\n463\n53\n2\n-86.0\n906.0'],
 ['410\n2013-11-25\n464\n54\n2\n-84.0\n906.0'],
 ['412\n2013-11-26\n465\n54\n2\n-85.0\n906.0'],
 ['415\n2013-11-27\n466\n55\n2\n-85.0\n907.0'],
 ['411\n2013-11-28\n467\n55\n2\n-84.0\n907.0'],
 ['414\n2013-11-29\n468\n55\n2\n-85.0\n907.0'],
 ['413\n2013-11-30\n469\n56\n2\n-85.0\n908.0'],
 ['475\n2013-12-02\n470\n56\n2\n-85.0\n907.0'],
 ['479\n2013-12-03\n471\n57\n2\n-84.0\n906.0'],
 ['416\n2013-12-04\n472\n57\n2\n-84.0\n907.0'],
 ['417\n2013-12-05\n473\n58\n2\n-86.0\n907.0'],
 ['420\n2013-12-06\n474\n58\n2\n-84.0\n906.0'],
 ['419\n2013-12-07\n475\n59\n2\n-85.0\n906.0'],
 ['418\n2013-12-08\n476\n59\n2\n-85.0\n906.0'],
 ['421\n2013-12-09\n477\n60\n3\n-85.0\n907.0'],
 ['422\n2013-12-18\n486\n64\n3\n-84.0\n904.0'],
 ['473\n2013-12-19\n487\n64\n3\n-85.0\n904.0'],
 ['480\n2013-12-20\n488\n64\n3\n-87.0\n903.0'],
 ['423\n2013-12-21\n489\n65\n3\n-85.0\n904.0'],

In [12]:
# Create a Pandas DataFrame by using the list of rows and a list of the column names

In [13]:
# Confirm DataFrame was created successfully

### Step 4: Prepare Data for Analysis

Examine the data types that are currently associated with each column. If necessary, cast (or convert) the data to the appropriate `datetime`, `int`, or `float` data types.

  > **Hint** You can use the Pandas `astype` and `to_datetime` methods to accomplish this task.

In [14]:
# Examine data type of each column

In [15]:
# Change data types for data analysis

In [16]:
# Confirm type changes were successful by examining data types again

### Step 5: Analyze the Data

Analyze your dataset by using Pandas functions to answer the following questions:

1. How many months exist on Mars?
2. How many Martian (and not Earth) days worth of data exist in the scraped dataset?
3. What are the coldest and the warmest months on Mars (at the location of Curiosity)? To answer this question:
    * Find the average the minimum daily temperature for all of the months.
    * Plot the results as a bar chart.
4. Which months have the lowest and the highest atmospheric pressure on Mars? To answer this question:
    * Find the average the daily atmospheric pressure of all the months.
    * Plot the results as a bar chart.
5. About how many terrestrial (Earth) days exist in a Martian year? To answer this question:
    * Consider how many days elapse on Earth in the time that Mars circles the Sun once.
    * Visually estimate the result by plotting the daily minimum temperature.

In [17]:
# 1. How many months are there on Mars?

In [18]:
# 2. How many Martian days' worth of data are there?

In [19]:
# 3. What is the average low temperature by month?

In [20]:
# Plot the average temperature by month

In [21]:
# Identify the coldest and hottest months in Curiosity's location

In [22]:
# 4. Average pressure by Martian month

In [23]:
# Plot the average pressure by month

In [24]:
# 5. How many terrestrial (earth) days are there in a Martian year?

On average, the third month has the coldest minimum temperature on Mars, and the eighth month is the warmest. But it is always very cold there in human terms!

Atmospheric pressure is, on average, lowest in the sixth month and highest in the ninth.

The distance from peak to peak is roughly 1425-750, or 675 days. A year on Mars appears to be about 675 days from the plot. Internet search confirms that a Mars year is equivalent to 687 earth days.

### Step 6: Save the Data

Export the DataFrame to a CSV file.

In [25]:
# Write the data to a CSV

In [26]:
browser.quit()